### ISSUE TITLE
Answer geographic questions on this data set

### ISSUE THREAD

**Issue by jaredgreene1** [jaredgreene1/NetworksOfGuatemala#14]
**Goal**:  Answer the following questions:
- [x] Is this dataset collected throughout the country?
- [ ] Can we access the municipality for each survey?

**Relevant resources**:
https://www.ine.gob.gt/index.php/encuestas/empleo-e-ingresos

**Comment by alex232890** [comment]
We cannot access the municipality data for this survey.
