### ISSUE TITLE
Perform lit review for commuting patterns

### ISSUE THREAD

**Issue by jaredgreene1** [jaredgreene1/NetworksOfGuatemala#2]
**Goal**: Perform lit review for studying commuting patterns (especially with Call Detail Records)

**Comment by jaredgreene1** [comment]
Helpful paper: google.com #5

**Comment by theodorehadges** [comment]
[Mobile Phones in a Traffic Flow: A Geographical Perspective to Evening Rush Hour Traffic Analysis Using Call Detail Records
](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0049171)**Summary: Uses CDR to assess composition of traffic flow during rush hour**

How is data presented?
- validate CDR data with traffic counter data (show line graph): Figure 3
- show line/bar graph where red line is Mon-Thur traffic and blue line is Friday traffic. Bars show percent difference between (mon-thur) and (friday): Figure 4
- show overall distribution against (mon-thur evening rush hour) and (fri evening rush hour): Figure 5

Notes:

- This CDR data has geolocation of cell towers
- Uses 2/7 anchor points of the [anchor point model](https://scholar.google.com/scholar?q=Using+Mobile+Positioning+Data+to+Model+Locations+Meaningful+to+Users+of+Mobile+Phones+Ahas+2010) to classify each call activity
  - home anchor point: probable location of the respondent’s home
  - work-time location: the respondent’s probable work-time location

**Comment by jaredgreene1** [comment]
Interesting that they studied a single road section and they make a case for a month of behavior being sufficient for estimating normal monthly activity.

Also includes references that may be helpful for supporting the use of CDRs to estimate home and work locations. 

Nice find.

**Comment by alex232890** [comment]
Relevant paper: http://documents.worldbank.org/curated/en/122541487082260120/pdf/WPS7969.pdf
- They used call data records in Guatemala to track consumption, mobility, and social patterns

**Comment by theodorehadges** [comment]
Powerpoint summary:
http://helper.ipam.ucla.edu/publications/caws3/caws3_13211.pdf
