### ISSUE TITLE
Review Existing Lit for Remittance Data

### ISSUE THREAD

**Issue by alex232890** [jaredgreene1/NetworksOfGuatemala#6]
**Goal**:  Research existing studies, surveys, etc related to remittances in Guatemala
**Relevant resources**: https://www.icpsr.umich.edu/index.html
- If you are a member of an organization affiliated with ICPSR, then you can access the datasets they have available
- Can search their datasets by geographic location

**Comment by alex232890** [comment]
https://publications.iadb.org/bitstream/handle/11319/7869/Remittance-Recipients-in-Guatemala.pdf?sequence=2
- Breaks down remittance recipients by region and demographics in Guatemala and also mentions that they received their data from the ENCOVI survey
- Good data visualization in here of the ENCOVI data which could be useful as a visual aid and/or reference while we go through the data ourselves

https://www.cbd.int/financial/charity/guatemala-remittance.pdf 
- Goes over the relationship between migrant location in the United States and how much and where they send money to in Guatemala (includes a map as a visual aid)

http://www.thedialogue.org/wp-content/uploads/2017/02/Remittances-2016-FINAL-DRAFT.pdf
- Includes information about the rise of internet/mobile-based transfers and the benefits of them and the analysis on how they will increase in the future is interesting

https://www.millicom.com/media/3009/mda-q2_2017.pdf
- Information about Tigo’s products including Tigo Money which allows for remittances on mobile devices, also talks about how “inflation rates, rates of GDP growth and remittance levels affect our business, financial condition and results of operations”

**Comment by jaredgreene1** [comment]
Encovi data: https://www.ine.gob.gt/index.php/encuestas-de-hogares-y-personas/condiciones-de-vida
